style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/wellingtonking/terraform-digitalocean-vpc
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
